#!/bin/bash
#PBS -N SAPEQablm
#PBS -P e14
#PBS -l ncpus=192
#PBS -l mem=150GB
#PBS -l walltime=03:00:00
#PBS -l wd
#PBS -q normal
#PBS -M r.holmes@unsw.edu.au
#PBS -l storage=scratch/e14+gdata/e14
#PBS -m e
#PBS -e OUT/pbs_sapeq.err
#PBS -o OUT/pbs_sapeq.out

module load intel-compiler/2019.5.281
module load netcdf/4.7.1
module load openmpi/4.0.1

mpirun -np 192 oceanM sapeq_ABLMe.in > OUT/sapeq_ABLMe.out

